name: Build Geode Mod

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: ubuntu-latest
          target: Win64

        - name: macOS
          os: macos-latest

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Este paso es VITAL: instala el SDK para que CMake lo encuentre
      - name: Setup Geode SDK
        uses: geode-sdk/setup-geode@v3

      - name: Build the mod
        uses: hiimjasmine00/build-geode-mod@xwin
        with:
          build-config: 'Release'
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']
    if: success()

    steps:
      - name: Combine Outputs
        uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Greensleep-Menu-Build
          path: ${{ steps.build.outputs.build-output }}
